### ISSUE TITLE
Deprecate tnrs()

### ISSUE THREAD

**Issue by kamapu** [ropensci/taxlist#10]
Function `tnrs()` is defunct in `taxize`. A new function `iPlant...` is replacing it and may be also implemented in `taxlist`

**Comment by r2j2ritson** [comment]
any updates on the tnrs() replacement?

**Comment by kamapu** [comment]
Oh, no! I didn't care on this issue until now but if you are using `taxlist` I can try to solve it in GitHub, at least.

**Comment by r2j2ritson** [comment]
Thanks @kamapu ! I'm analyzing present/absence on a statewide level with large plant datasets and trying to rectify plant synonyms into unique IDs. taxlist, particularly tnrs(), seems like a great solution!

**Comment by kamapu** [comment]
If it is just to rectify synonyms, you rather check the package [`taxize`](https://github.com/ropensci/taxize) directly. There you will find the function `iPlant()` among others.
The package `taxlist` will be useful if you like to preserve the synonyms as a part of taxonomic concepts and if you like to include also hierarchies (taxonomic ranks).

**Comment by r2j2ritson** [comment]
Awesome! Thanks for your help!
