### ISSUE TITLE
New function to exchange data using the Darwing Core Standard

### ISSUE THREAD

**Issue by kamapu** [ropensci/taxlist#37]
New functions are needed to import and export data using the Darwin Core Standard. These functions may depend on functions of the package [taxastand](https://github.com/joelnitta/taxastand).

**Comment by kamapu** [comment]
Some aspects to consider on developing the new functions:
- As far as I know, CRAN does not allow dependencies that are not submitted and accepted in CRAN.
- There is already a function called `df2taxlist()` but I plan to do some improvements on it.
- There are also some coercion methods such as `df <- as(taxlist, "data.frame")`

**Comment by kamapu** [comment]
I suggest to define a separated function, such as `dwc2taxlist()` or similar. Function `df2taxlist()` is written as a data.frame-method and checks mandatory columns in the input data. Once ready, we can insert a check in `df2taxlist()` that can recognize a standard column form DWC and automatically use this function to create the taxlist object. It is only an idea, though.

**Comment by joelnitta** [comment]
Update: [dwctaxon](https://github.com/ropensci/dwctaxon) is now on [CRAN](https://cran.r-project.org/web/packages/dwctaxon/index.html), so can be used as a dependency if needed.

**Comment by kamapu** [comment]
Time has passed @joelnitta. I was looking at a vignette for `dwctaxon` and noticed that you use tibbles as the class for the tables you handle. I am afraid that including `dwctaxon` as a dependency for `taxlist` might imply that several packages from **tidyverse** become dependencies for `taxlist` as well, and I would like to avoid that. Instead, I will take care of the coercion routines for data.frames, which need to take Darwin Core into account. From there to tibble may be just one more step.

**Comment by kamapu** [comment]
TODO:
- [ ] A function `taxlist2df()` with an alternative use of the Darwin Core to call columns
- [ ] Include the same alternative to `df2taxlist()` in the reverse way
- [ ] Include these functions in the coersion-methods (`as()`)
- [ ] Write a tutorial for getting data from one to the another format.

**Comment by kamapu** [comment]
Hier it is the conversion table used by `taxlist`:

```r
taxlist:::dwc_table
```

```txt
                       dwc        taxlist
1                  taxonID TaxonConceptID
2         scientificNameID   TaxonUsageID
3      acceptedNameUsageID   AcceptedName
4      originalNameUsageID       Basionym
5        nameAccordingToID         ViewID
6           scientificName      TaxonName
7                taxonRank          Level
8 scientificNameAuthorship     AuthorName

```
