### ISSUE TITLE
test and vignettes errors

### ISSUE THREAD

**Issue by maelle** [ropensci/taxlist#39]
:wave: @kamapu! I noticed errors via https://ropensci.r-universe.dev/builds (same as https://github.com/ropensci/taxlist/actions/runs/4248400805/jobs/7387530379)

Is any help needed?

**Comment by kamapu** [comment]
The error was caused by a dependency of the development version to `biblio (>= 0.0.8)` and is solved by 
5a2037d.

**Comment by maelle** [comment]
thank you! :rocket:
